<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{

	/*
	 * Overwrite default findAll, to orderby name
	 * @return ArrayList of Clients
	 */
	public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }
}
