<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeedRepository extends EntityRepository
{
	public function getDates($id) 
	{
		$query = $this->createQueryBuilder('ptu')
    					->where('s.name = :status')
    					->andwhere('p.id = :project')
    					->setParameter('status', 'A venir')
    					->setParameter('project', $projectid)
						->leftJoin('ptu.project', 'p')
						->leftJoin('ptu.status', 's')
					    ->orderBy('ptu.position', 'ASC')
					    ->setMaxResults(1)
					    ->getQuery();


	    return $query->getOneOrNullResult();
	}
}
