<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function findPreciselyBy($category = null, $status = null, $user = null) 
	{
		$query = $this->createQueryBuilder('p')
						->add('where','p.id > 0');

		if($category) {
			$query->leftJoin('p.category', 'c')
					->andWhere('c.id = :category')
	                ->setParameter('category', $category);
	    }
	    if($user) {
	        $query->leftJoin('p.users', 'u')
	        		->andWhere($query->expr()->in('u', ':user'))
	                ->setParameter('user', $user);
	    }
	    if($status) {
			$query->leftJoin('p.status', 's')
					->andWhere('s.id = :status')
	                ->setParameter('status', $status);
	    }

        return $query->getQuery()
                      ->getResult();
	}
}
