<?php

namespace Flyd\DashboardBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * ProjectTaskUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTaskUserRepository extends EntityRepository
{
	/*
	 * Recherche la prochaine tâche En cours
	 */
	public function getFirstPendingTask($projectid)
	{

		$query = $this->createQueryBuilder('ptu')
    					->where('s.name LIKE :status')
    					->andwhere('p.id = :project')
    					->setParameter('status', '%En cours%')
    					->setParameter('project', $projectid)
						->leftJoin('ptu.project', 'p')
						->leftJoin('ptu.status', 's')
					    ->orderBy('ptu.position', 'ASC')
					    ->setMaxResults(1)
					    ->getQuery();


	    return $query->getOneOrNullResult();
	}

	/*
	 * Recherche la prochaine tâche à venir
	 */
	public function getFirstComingTask($projectid)
	{

		$query = $this->createQueryBuilder('ptu')
    					->where('s.name = :status')
    					->andwhere('p.id = :project')
    					->setParameter('status', 'A venir')
    					->setParameter('project', $projectid)
						->leftJoin('ptu.project', 'p')
						->leftJoin('ptu.status', 's')
					    ->orderBy('ptu.position', 'ASC')
					    ->setMaxResults(1)
					    ->getQuery();


	    return $query->getOneOrNullResult();
	}
}
