<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends EntityRepository
{
	public function getSupplierList() {
		return $this
		    ->createQueryBuilder('a')
            ->addSelect(array('a.id','a.name', 'a.job'))
		    ->getQuery()
		    ->getResult()
		  ;
	}
}
