<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends EntityRepository
{
	/**
     * get Suppliers without
     *
     * @return array
     */
	public function getSuppliersWithout($existingsuppliers) {

		$query = $this->createQueryBuilder('a')
                      ->select(array('a.id', 'a.name', 'a.job'));

		if(count($existingsuppliers) != 0) {
			$tab = array();
			foreach ($existingsuppliers as $value) {
				$tab[] = $value->getId();
			}

	        $query = $query->add('where', $query->expr()->notIn('a', ':c'))
	                      ->setParameter('c', $tab);
	    }
        return $query->getQuery()
                      ->getResult();
        
	}

	/*
	 * Overwrite default findAll, to orderby name
	 *
	 * @return array
	 */
	public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }
}
