<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	/**
     * get Task Identifiers
     *
     * @return array
     */
	public function getTaskIdentifiers() {
		return $this
		    ->createQueryBuilder('a')
            ->addSelect(array('a.id','a.name','a.step'))
		    ->getQuery()
		    ->getResult()
		  ;
	}
}
