<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{


	public function getUsersWithout($existingusers) 
	{
		$query = $this->createQueryBuilder('a')
                      ->select(array('a.id', 'a.username', 'a.job'));

		if(count($existingusers) != 0) {
			$tab = array();
			foreach ($existingusers as $value) {
				$tab[] = $value->getId();
			}

	        $query = $query->add('where', $query->expr()->notIn('a', ':c'))
	                      ->setParameter('c', $tab);		
		}

		return $query->getQuery()
                      ->getResult();
        
	}
}
