<?php

namespace Flyd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{


	public function getUsersWithout($existingusers) {

		foreach ($existingusers as $value) {
			$tab[] = $value->getId();
		}

		$query = $this->createQueryBuilder('a')
                      ->select(array('a.id', 'a.username', 'a.job'));
        $query = $query->add('where', $query->expr()->notIn('a', ':c'))
                      ->setParameter('c', $tab)
                      ->getQuery()
                      ->getResult();
        return $query;
	}
}
